### ISSUE TITLE
GPU volatile utility change frequently from very low to high during trainning periodicaly

### ISSUE THREAD

**Issue by HarukiZhang** [ZX-Yin/ms-nerf#3]
During the whole training, volatile GPU-utility will change periodically within 2-3 sec from 10% to 99%.

I just wonder is this behaviour a normal running of the code, or some configuration I did not make it right?
The problem is that the running of this code will make my GPU coil whine, which will not happen even when I stress test my GPU, neither will happen when running other NeRF-like GPU-full-load trainning task.

My system only has one GPU (CUDA11.8) and OS is ubuntu 20.04, and I changed no argument in the provided training shell scripts or the python code.

Please note that this is only a polite ask (not a complaint).

**Comment by ZX-Yin** [comment]
Thank you for interest!

This is normal, and I also encountered this problem when runing my code and [multinerf](https://github.com/google-research/multinerf). I guess it may be due to the periodical log behavior, as it happens every 100 iters, which exactly takes 2~3 seconds.

Please let me know if you have more questions. :)

**Comment by ZX-Yin** [comment]
I'm closing this issue. If you have any other questions, please feel free to open a new issue.
